controllers:
<<<<<<< HEAD
    resource: ../src/Controller/
    type: annotation

homepage:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /
    controller: App\Controller\SecurityController::login
    
register:
    path: /
    controller: App\Controller\SecurityController::register
    
=======
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
>>>>>>> ancien-master
