controllers:
    resource: ../src/Controller/
    type: annotation

homepage:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /
    controller: App\Controller\SecurityController::login
    
register:
    path: /
    controller: App\Controller\SecurityController::register
    